test:
  sessions:
    default:
      database: prioridata_challenge_test
      hosts:
        - localhost:27017
      logger: true

development:
  sessions:
    default:
      database: prioridata_challenge_development
      hosts:
        - localhost:27017
      logger: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      logger: true
